[package]
name = "paracosm"
version = "0.1.0"
edition = "2021"
description = "Paracosm Engine Project"
exclude = ["crates/"]
authors = ["Exsolutus <exsolutus.dev@gmail.com>"]
license = "MIT OR Apache-2.0"

[workspace]
members = [
    "crates/*"
]
resolver = "2"
