[package]
name = "paracosm_gpu_macros"
version = "0.1.0"
publish = true
authors = ["Exsolutus <exsolutus.dev@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = ""

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = "2.0.74"
